//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp3._2.moi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="moi.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperature", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureResponse")]
        string Meteo_GetTemperature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperature", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureResponse")]
        System.Threading.Tasks.Task<string> Meteo_GetTemperatureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperatureDay", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureDayResponse")]
        System.Data.DataSet Meteo_GetTemperatureDay(string dateTempSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperatureDay", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureDayResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Meteo_GetTemperatureDayAsync(string dateTempSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperatureByDate", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureByDateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="temp")]
        string Meteo_GetTemperatureByDate(string dateTempSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Meteo_GetTemperatureByDate", ReplyAction="http://tempuri.org/IService/Meteo_GetTemperatureByDateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="temp")]
        System.Threading.Tasks.Task<string> Meteo_GetTemperatureByDateAsync(string dateTempSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        tp3._2.moi.CompositeType GetDataUsingDataContract(tp3._2.moi.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<tp3._2.moi.CompositeType> GetDataUsingDataContractAsync(tp3._2.moi.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : tp3._2.moi.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<tp3._2.moi.IService>, tp3._2.moi.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string Meteo_GetTemperature() {
            return base.Channel.Meteo_GetTemperature();
        }
        
        public System.Threading.Tasks.Task<string> Meteo_GetTemperatureAsync() {
            return base.Channel.Meteo_GetTemperatureAsync();
        }
        
        public System.Data.DataSet Meteo_GetTemperatureDay(string dateTempSearch) {
            return base.Channel.Meteo_GetTemperatureDay(dateTempSearch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Meteo_GetTemperatureDayAsync(string dateTempSearch) {
            return base.Channel.Meteo_GetTemperatureDayAsync(dateTempSearch);
        }
        
        public string Meteo_GetTemperatureByDate(string dateTempSearch) {
            return base.Channel.Meteo_GetTemperatureByDate(dateTempSearch);
        }
        
        public System.Threading.Tasks.Task<string> Meteo_GetTemperatureByDateAsync(string dateTempSearch) {
            return base.Channel.Meteo_GetTemperatureByDateAsync(dateTempSearch);
        }
        
        public tp3._2.moi.CompositeType GetDataUsingDataContract(tp3._2.moi.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<tp3._2.moi.CompositeType> GetDataUsingDataContractAsync(tp3._2.moi.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
